In [38]:
import pandas as pd
import numpy as np
from sklearn.neighbors import NearestNeighbors
import ast
from collections import defaultdict
from sklearn.metrics import r2_score
from scipy.stats import spearmanr
import copy
import importlib
import time
import json
import requests
import unicodedata



import scripts.cleaning as cleaning
import scripts.knn_class as knn_class
import scripts.eval as eval

In [39]:
importlib.reload(knn_class)

In [40]:
filename = "2025_F1_Races - 20263.csv"
df_dict = cleaning.import_and_clean(filename)
# df_dict
df = cleaning.format_testing(df_dict)
# df.to_csv(f"testing2026.csv", index = False)
df

,driver,prev5_avg,prev5_points,points_behind_leader,current_points,percent_of_max,position,race_number
0,A. AntonelliMercedes,0.0,[],7.0,18.0,0.720000,2,1
1,G. RussellMercedes,0.0,[],0.0,25.0,1.000000,1,1
2,L. HamiltonFerrari,0.0,[],13.0,12.0,0.480000,4,1
3,C. LeclercFerrari,0.0,[],10.0,15.0,0.600000,3,1
4,L. NorrisMcLaren,0.0,[],15.0,10.0,0.400000,5,1
...,...,...,...,...,...,...,...,...
193,F. AlonsoAston Martin Racing,0.2,"[0.0, 0.0, 1.0, 0.0, 0.0]",178.0,1.0,0.005587,18,9
194,N. HulkenbergAudi,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",179.0,0.0,0.000000,19,9
195,V. BottasCadillac F1 Team,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",179.0,0.0,0.000000,20,9
196,S. PerezCadillac F1 Team,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",179.0,0.0,0.000000,21,9
197,L. StrollAston Martin Racing,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0]",179.0,0.0,0.000000,22,9

In [41]:
df["prev5_points"] = (
    df.groupby("driver", sort=False)["prev5_points"]
      .shift(-1)
)

df["prev5_points"] = df["prev5_points"].apply(
    lambda x: x if isinstance(x, list) else []
)

df["prev5_avg"] = (
    df.groupby("driver", sort=False)["prev5_avg"]
      .shift(-1)
)

# df["prev5_avg"] = df["prev5_avg"].apply(
#     lambda x: x if isinstance(x, list) else []
# )
df

,driver,prev5_avg,prev5_points,points_behind_leader,current_points,percent_of_max,position,race_number
0,A. AntonelliMercedes,18.0,[18.0],7.0,18.0,0.720000,2,1
1,G. RussellMercedes,25.0,[25.0],0.0,25.0,1.000000,1,1
2,L. HamiltonFerrari,12.0,[12.0],13.0,12.0,0.480000,4,1
3,C. LeclercFerrari,15.0,[15.0],10.0,15.0,0.600000,3,1
4,L. NorrisMcLaren,10.0,[10.0],15.0,10.0,0.400000,5,1
...,...,...,...,...,...,...,...,...
193,F. AlonsoAston Martin Racing,NaN,[],178.0,1.0,0.005587,18,9
194,N. HulkenbergAudi,NaN,[],179.0,0.0,0.000000,19,9
195,V. BottasCadillac F1 Team,NaN,[],179.0,0.0,0.000000,20,9
196,S. PerezCadillac F1 Team,NaN,[],179.0,0.0,0.000000,21,9
197,L. StrollAston Martin Racing,NaN,[],179.0,0.0,0.000000,22,9

In [42]:
# df = df[df["race_number"] == 8]
# result = df.set_index("driver").to_dict(orient="index")
# with open("drivers.json", "w") as f:
#     json.dump(result, f, indent=4)

In [43]:
def update_predictions2(completed_race, year = 2026, year_races = 22, sims = 10000):
    knn_sim = knn_class.KNNSeasonSimulator()
    knn_sim.set_neighbors(year)

    # change this to read json and covert to pandas
    # with open('training_data/current_standings.json', 'r', encoding='utf-8') as file:
    #     data = json.load(file)
    # df_eval = pd.DataFrame.from_dict(data, orient='index').reset_index().rename(columns={'index': 'driver'})
    # df_eval['prev5_points'] = df_eval['prev5_points'].apply(ast.literal_eval)
    df_eval = df

    all_sims = []
    num_races = year_races
    # print(df_eval)
    df_eval_small = (df_eval[df_eval.race_number == completed_race]).set_index("driver").to_dict(orient='index')
    res = []
    for j in range(sims):
        if j % 1000 == 0:
            print(j, completed_race)
        df_sim = copy.deepcopy(df_eval_small)
        # print(df_sim)
        # print(completed_race)
        df_sim = knn_sim.simulate_season(df_sim, num_races)

        res.append({
            d: df_sim[d]["current_points"]
            for d in df_sim  
        })

    all_sims.append(res)

    data = defaultdict(lambda: defaultdict(int))
    for i in range(sims):
        d = all_sims[0][i]

        sort = dict(sorted(d.items(), key=lambda item: item[1], reverse=True))
        c = 1
        for k,v in sort.items():
            if c == 1:
                data[k]["1st"] += 100 * 1/sims
            if c <= 3:
                data[k]["Podium"] += 100 * 1/sims
            if c <= 5:
                data[k]["Top 5"] += 100 * 1/sims
            if c <= 10:
                data[k]["Top 10"] += 100 * 1/sims
            
            data[k]["points"] += v/sims
            
            c += 1

    # url = "https://api.jolpi.ca/ergast/f1/2026/driverStandings.json"

    # response = requests.get(url)
    
    # data2 = response.json()["MRData"]["StandingsTable"]
    
    # data["completed race"] = completed_race + 1
    # data["point total"] = total_points(data2["StandingsLists"][0]["DriverStandings"])

    # json_string = json.dumps(data, indent=4)
    # with open("json/predictions.json", "w") as file:
    #     file.write(json_string)
    return data

In [44]:
d = {}
for i in range(5, 9):
    d[str(i)] = update_predictions2(i, year = 2026, year_races = 22, sims = 10000)

0 5
1000 5
2000 5
3000 5
4000 5
5000 5
6000 5
7000 5
8000 5
9000 5
0 6
1000 6
2000 6
3000 6
4000 6
5000 6
6000 6
7000 6
8000 6
9000 6
0 7
1000 7
2000 7
3000 7
4000 7
5000 7
6000 7
7000 7
8000 7
9000 7
0 8
1000 8
2000 8
3000 8
4000 8
5000 8
6000 8
7000 8
8000 8
9000 8

In [45]:
json_string = json.dumps(d, indent=4)
with open("json/all_predictions.json", "w") as file:
    file.write(json_string)
print(json_string)

{
    "5": {
        "A. AntonelliMercedes": {
            "1st": 96.74000000001259,
            "Podium": 99.99000000001425,
            "Top 5": 100.00000000001425,
            "Top 10": 100.00000000001425,
            "points": 460.1664000000008
        },
        "G. RussellMercedes": {
            "Podium": 82.28000000000519,
            "Top 5": 99.18000000001383,
            "Top 10": 100.00000000001425,
            "points": 305.28079999999926,
            "1st": 2.6399999999999877
        },
        "L. HamiltonFerrari": {
            "Podium": 42.83000000000005,
            "Top 5": 93.29000000001082,
            "Top 10": 100.00000000001425,
            "points": 240.54990000000072,
            "1st": 0.16
        },
        "C. LeclercFerrari": {
            "Top 5": 96.02000000001222,
            "Top 10": 100.00000000001425,
            "points": 256.2310000000014,
            "Podium": 55.759999999997476,
            "1st": 0.45000000000000023
        },
        "L. NorrisMcLaren": {
            "Top 5": 75.41000000000167,
            "Top 10": 100.00000000001425,
            "points": 197.71169999999972,
            "Podium": 15.559999999999713,
            "1st": 0.01
        },
        "M. VerstappenRed Bull Racing": {
            "Top 10": 99.98000000001424,
            "points": 110.4098,
            "Top 5": 10.839999999999813,
            "Podium": 0.8900000000000006
        },
        "O. PiastriMcLaren": {
            "Top 10": 100.00000000001425,
            "points": 140.3694000000004,
            "Top 5": 25.26000000000115,
            "Podium": 2.6899999999999866
        },
        "O. BearmanHaas F1 Team": {
            "Top 10": 58.85999999999686,
            "points": 42.56560000000019
        },
        "I. HadjarRed Bull Racing": {
            "Top 10": 40.880000000000436,
            "points": 36.65629999999986
        },
        "L. LawsonRacing Bulls": {
            "Top 10": 49.54999999999871,
            "points": 39.423899999999996
        },
        "P. GaslyAlpine": {
            "points": 44.91840000000049,
            "Top 10": 68.92999999999836
        },
        "A. LindbladRacing Bulls": {
            "points": 21.39940000000001,
            "Top 10": 7.589999999999883
        },
        "F. ColapintoAlpine": {
            "points": 37.8966000000001,
            "Top 10": 43.03000000000001
        },
        "C. SainzWilliams": {
            "points": 23.21970000000012,
            "Top 10": 9.049999999999851
        },
        "V. BottasCadillac F1 Team": {
            "points": 10.387799999999794,
            "Top 10": 1.8300000000000014
        },
        "N. HulkenbergAudi": {
            "points": 12.122199999999795,
            "Top 10": 2.0899999999999994
        },
        "A. AlbonWilliams": {
            "points": 16.634399999999754,
            "Top 10": 4.319999999999952
        },
        "S. PerezCadillac F1 Team": {
            "points": 8.71639999999988,
            "Top 10": 1.0600000000000007
        },
        "L. StrollAston Martin Racing": {
            "points": 8.098199999999883,
            "Top 10": 1.2300000000000009
        },
        "G. BortoletoAudi": {
            "points": 17.805299999999956,
            "Top 10": 4.559999999999947
        },
        "E. OconHaas F1 Team": {
            "points": 15.91759999999965,
            "Top 10": 3.8299999999999623
        },
        "F. AlonsoAston Martin Racing": {
            "points": 13.758199999999798,
            "Top 10": 3.2099999999999755
        }
    },
    "6": {
        "A. AntonelliMercedes": {
            "1st": 99.7000000000141,
            "Podium": 100.00000000001425,
            "Top 5": 100.00000000001425,
            "Top 10": 100.00000000001425,
            "points": 465.9059000000015
        },
        "G. RussellMercedes": {
            "Podium": 70.88999999999936,
            "Top 5": 98.7300000000136,
            "Top 10": 100.00000000001425,
            "points": 255.14810000000082,
            "1st": 0.13999999999999999
        },
        "C. LeclercFerrari": {
            "Podium": 39.00000000000081,
            "Top 5": 94.78000000001158,
            "Top 10": 100.00000000001425,
            "points": 223.60060000000013,
            "1st": 0.03
        },
        "L. HamiltonFerrari": {
            "Top 5": 99.29000000001389,
            "Top 10": 100.00000000001425,
            "points": 266.5395000000005,
            "Podium": 78.42000000000321,
            "1st": 0.12999999999999998
        },
        "L. NorrisMcLaren": {
            "Top 5": 54.28999999999777,
            "Top 10": 100.00000000001425,
            "points": 159.82919999999996,
            "Podium": 5.9999999999999165
        },
        "O. PiastriMcLaren": {
            "Top 10": 100.00000000001425,
            "points": 157.25390000000058,
            "Top 5": 50.50999999999852,
            "Podium": 5.639999999999924
        },
        "M. VerstappenRed Bull Racing": {
            "Top 10": 99.72000000001411,
            "points": 80.13540000000059,
            "Top 5": 2.389999999999993,
            "Podium": 0.05
        },
        "F. ColapintoAlpine": {
            "Top 10": 20.630000000000425,
            "points": 35.97930000000013
        },
        "P. GaslyAlpine": {
            "Top 10": 95.36000000001188,
            "points": 62.35460000000036,
            "Top 5": 0.01
        },
        "L. LawsonRacing Bulls": {
            "Top 10": 61.46999999999634,
            "points": 47.8495000000005
        },
        "I. HadjarRed Bull Racing": {
            "points": 51.07410000000026,
            "Top 10": 72.98000000000043
        },
        "A. AlbonWilliams": {
            "points": 20.09410000000008,
            "Top 10": 2.3099999999999947
        },
        "O. BearmanHaas F1 Team": {
            "points": 39.670499999999954,
            "Top 10": 29.890000000001873
        },
        "A. LindbladRacing Bulls": {
            "points": 28.483200000000107,
            "Top 10": 9.059999999999851
        },
        "E. OconHaas F1 Team": {
            "points": 17.964999999999897,
            "Top 10": 1.9900000000000015
        },
        "L. StrollAston Martin Racing": {
            "points": 7.129299999999924,
            "Top 10": 0.2900000000000001
        },
        "N. HulkenbergAudi": {
            "points": 10.955199999999872,
            "Top 10": 0.46000000000000024
        },
        "G. BortoletoAudi": {
            "points": 16.216799999999886,
            "Top 10": 1.400000000000001
        },
        "S. PerezCadillac F1 Team": {
            "points": 7.788199999999958,
            "Top 10": 0.35000000000000014
        },
        "C. SainzWilliams": {
            "points": 20.828100000000145,
            "Top 10": 2.6399999999999877
        },
        "V. BottasCadillac F1 Team": {
            "points": 9.351799999999823,
            "Top 10": 0.36000000000000015
        },
        "F. AlonsoAston Martin Racing": {
            "points": 13.740399999999678,
            "Top 10": 1.0900000000000007
        }
    },
    "7": {
        "A. AntonelliMercedes": {
            "1st": 93.96000000001116,
            "Podium": 99.99000000001425,
            "Top 5": 100.00000000001425,
            "Top 10": 100.00000000001425,
            "points": 445.85819999999984
        },
        "L. HamiltonFerrari": {
            "Podium": 93.74000000001105,
            "Top 5": 99.73000000001412,
            "Top 10": 100.00000000001425,
            "points": 340.27279999999945,
            "1st": 5.099999999999936
        },
        "G. RussellMercedes": {
            "Podium": 82.48000000000529,
            "Top 5": 99.27000000001388,
            "Top 10": 100.00000000001425,
            "points": 291.4586000000001,
            "1st": 0.9300000000000006
        },
        "O. PiastriMcLaren": {
            "Top 5": 47.89999999999904,
            "Top 10": 100.00000000001425,
            "points": 180.41379999999938,
            "Podium": 3.8699999999999615,
            "1st": 0.01
        },
        "C. LeclercFerrari": {
            "Top 5": 74.38000000000115,
            "Top 10": 100.00000000001425,
            "points": 207.31139999999974,
            "Podium": 10.809999999999814
        },
        "L. NorrisMcLaren": {
            "Top 10": 100.00000000001425,
            "points": 201.6625,
            "Top 5": 70.189999999999,
            "Podium": 8.969999999999853
        },
        "M. VerstappenRed Bull Racing": {
            "Top 10": 100.00000000001425,
            "points": 123.68730000000026,
            "Top 5": 8.529999999999863,
            "Podium": 0.13999999999999999
        },
        "I. HadjarRed Bull Racing": {
            "Top 10": 91.16000000000973,
            "points": 60.80620000000043
        },
        "P. GaslyAlpine": {
            "Top 10": 98.27000000001337,
            "points": 68.16610000000024
        },
        "A. LindbladRacing Bulls": {
            "Top 10": 7.849999999999877,
            "points": 30.95119999999982
        },
        "O. BearmanHaas F1 Team": {
            "points": 38.114799999999995,
            "Top 10": 17.06999999999987
        },
        "L. LawsonRacing Bulls": {
            "points": 51.27760000000055,
            "Top 10": 68.12999999999795
        },
        "F. ColapintoAlpine": {
            "points": 35.62049999999997,
            "Top 10": 12.89999999999977
        },
        "E. OconHaas F1 Team": {
            "points": 16.81279999999992,
            "Top 10": 0.7900000000000005
        },
        "C. SainzWilliams": {
            "points": 19.77000000000014,
            "Top 10": 1.2400000000000009
        },
        "A. AlbonWilliams": {
            "points": 18.89980000000001,
            "Top 10": 0.9300000000000006
        },
        "S. PerezCadillac F1 Team": {
            "points": 7.098399999999966,
            "Top 10": 0.08
        },
        "V. BottasCadillac F1 Team": {
            "points": 8.799399999999956,
            "Top 10": 0.16
        },
        "N. HulkenbergAudi": {
            "points": 10.351999999999897,
            "Top 10": 0.21000000000000005
        },
        "L. StrollAston Martin Racing": {
            "points": 6.7398999999999125,
            "Top 10": 0.09999999999999999
        },
        "G. BortoletoAudi": {
            "points": 15.159699999999837,
            "Top 10": 0.6700000000000004
        },
        "F. AlonsoAston Martin Racing": {
            "points": 12.951599999999726,
            "Top 10": 0.4400000000000002
        }
    },
    "8": {
        "A. AntonelliMercedes": {
            "1st": 93.34000000001085,
            "Podium": 100.00000000001425,
            "Top 5": 100.00000000001425,
            "Top 10": 100.00000000001425,
            "points": 441.8124999999987
        },
        "G. RussellMercedes": {
            "Podium": 96.59000000001251,
            "Top 5": 99.87000000001419,
            "Top 10": 100.00000000001425,
            "points": 349.94579999999814,
            "1st": 5.079999999999936
        },
        "L. HamiltonFerrari": {
            "Podium": 91.60000000000996,
            "Top 5": 99.7100000000141,
            "Top 10": 100.00000000001425,
            "points": 315.87089999999944,
            "1st": 1.5800000000000012
        },
        "M. VerstappenRed Bull Racing": {
            "Top 5": 26.010000000001266,
            "Top 10": 100.00000000001425,
            "points": 163.78129999999996,
            "Podium": 0.8600000000000005
        },
        "L. NorrisMcLaren": {
            "Top 5": 56.83999999999726,
            "Top 10": 100.00000000001425,
            "points": 194.3984000000002,
            "Podium": 3.3099999999999734
        },
        "O. PiastriMcLaren": {
            "Top 10": 100.00000000001425,
            "points": 198.82200000000054,
            "Top 5": 60.80999999999647,
            "Podium": 4.129999999999956
        },
        "C. LeclercFerrari": {
            "Top 10": 100.00000000001425,
            "points": 194.8017999999999,
            "Top 5": 56.75999999999728,
            "Podium": 3.509999999999969
        },
        "P. GaslyAlpine": {
            "Top 10": 98.1400000000133,
            "points": 66.74550000000075
        },
        "I. HadjarRed Bull Racing": {
            "Top 10": 98.64000000001356,
            "points": 67.44010000000047
        },
        "L. LawsonRacing Bulls": {
            "Top 10": 71.7599999999998,
            "points": 51.40160000000042
        },
        "F. ColapintoAlpine": {
            "points": 34.263599999999784,
            "Top 10": 9.499999999999842
        },
        "O. BearmanHaas F1 Team": {
            "points": 36.83299999999993,
            "Top 10": 13.34999999999976
        },
        "F. AlonsoAston Martin Racing": {
            "points": 12.042899999999763,
            "Top 10": 0.22000000000000006
        },
        "C. SainzWilliams": {
            "points": 18.35180000000014,
            "Top 10": 0.5700000000000003
        },
        "A. LindbladRacing Bulls": {
            "points": 30.941299999999693,
            "Top 10": 5.989999999999917
        },
        "S. PerezCadillac F1 Team": {
            "points": 6.698500000000001,
            "Top 10": 0.09
        },
        "G. BortoletoAudi": {
            "points": 14.407299999999857,
            "Top 10": 0.3100000000000001
        },
        "E. OconHaas F1 Team": {
            "points": 15.985299999999897,
            "Top 10": 0.5900000000000003
        },
        "L. StrollAston Martin Racing": {
            "points": 6.03629999999992,
            "Top 10": 0.08
        },
        "A. AlbonWilliams": {
            "points": 17.87119999999999,
            "Top 10": 0.5000000000000002
        },
        "N. HulkenbergAudi": {
            "points": 9.70999999999987,
            "Top 10": 0.11999999999999998
        },
        "V. BottasCadillac F1 Team": {
            "points": 8.128200000000016,
            "Top 10": 0.13999999999999999
        }
    }
}